---
- name: "Ensure Services are Running"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - prometheus
    - prometheus-node-exporter
    - grafana-server
