---
- name: "Provision AWS Infrastructure"
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - aws-infra

- name: "Configure Web Application Stack"
  hosts: launched_ec2_nodes
  become: true
  gather_facts: true
  roles:
   - web-app
