aws_ec2_key_name: "web-stack-key"
aws_ec2_key_type: rsa

aws_ec2_name: "web-stack-ansible-instance"
aws_ec2_instance_type: "t3.micro"
aws_ec2_instance_volumes:
  - device_name: /dev/sdb
    ebs:
      volume_type: gp3
      volume_size: 20
      delete_on_termination: true
aws_ec2_instance_count: 1
aws_ec2_instance_wait: yes
aws_ec2_instance_wait_timeout: 500
aws_ec2_instance_public_ip: yes
