---
- name: "Manage AWS Infrastructure | Generate Local SSH Key Pair"
  community.crypto.openssh_keypair:
    path: "~/.ssh/ec2-key-pair"
    type: ed25519
  register: local_keypair

- name: "Manage AWS Infrastructure | Import Public Key To AWS"
  amazon.aws.ec2_key:
    name: "{{ aws_ec2_key_name }}"
    region: "{{ aws_region }}"
    key_material: "{{ local_keypair.public_key }}"
    state: present
