---
- name: "Manage AWS Infrastructure | AWS Route Table"
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ aws_vpc_info.vpc.id }}"
    tags: "{{ aws_default_tags }}"
    subnets:
      - "{{ aws_subnet.subnet.id }}"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ aws_vpc_igw_info.gateway_id }}"
    state: present
  register: aws_vpc_rt
