# Public Access Block, Bucket Versioning, Server-Side Encryption

---
- name: "Manage AWS Infrastructure | Deploy a S3 Bucket"
  amazon.aws.s3_bucket:
    name: "{{ aws_s3_bucket_name }}"
    versioning: "{{ aws_s3_bucket_versioning | default('true') }}"
    region: "{{ aws_region }}"
    encryption: "{{ aws_s3_bucket_encryption | deafult('AES256') }}"
    public_access:
      block_public_acls: true
      ignore_public_acls: true
    state: present
  register: aws_s3_bucket
