---
- name: "Manage AWS Infrastructure | Security Groups"
  amazon.aws.ec2_security_group:
    name: "{{ aws_sg_name }}"
    description: "{{ aws_sg_description }}"
    vpc_id: "{{ aws_vpc_info.vpc.id }}"
    tags: "{{ aws_default_tags | combine ( aws_default_sg_tags ) }}"
    rules:
      - proto: "tcp"
        ports:
          - 80
          - 443
        cidr_ip: "0.0.0.0/0"
        rule_desc: "Allow All on Ports HTTP/(S)"
      - proto: "tcp"
        ports:
          - 22
        cidr_ip: "0.0.0.0/24"
        rule_desc: "Allow SSH."
    state: present
